import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f9fafb',
    },
    headerGradient: {
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 16,
    },
    headerRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    headerLeft: {
        flex: 1,
    },
    logoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    logoIcon: {
        backgroundColor: '#d1fae5',
        padding: 10,
        borderRadius: 16,
        marginRight: 12,
    },
    logoText: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#111827',
    },
    logoHighlight: {
        color: '#059669',
    },
    dateText: {
        fontSize: 14,
        color: '#6b7280',
        marginTop: 2,
    },
    settingsButton: {
        backgroundColor: 'white',
        padding: 10,
        borderRadius: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 8,
        elevation: 2,
    },
    welcomeCard: {
        marginHorizontal: 20,
        marginTop: 8,
        marginBottom: 16,
    },
    welcomeGradient: {
        borderRadius: 24,
        padding: 20,
        shadowColor: '#0f766e',
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.2,
        shadowRadius: 16,
        elevation: 8,
    },
    welcomeRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    welcomeLeft: {
        flex: 1,
    },
    welcomeBadge: {
        color: 'rgba(255,255,255,0.9)',
        fontSize: 12,
        fontWeight: '500',
        marginBottom: 4,
    },
    welcomeName: {
        color: 'white',
        fontSize: 24,
        fontWeight: 'bold',
    },
    weatherContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 12,
    },
    weatherBadge: {
        backgroundColor: 'rgba(255,255,255,0.2)',
        borderRadius: 100,
        paddingHorizontal: 16,
        paddingVertical: 8,
        flexDirection: 'row',
        alignItems: 'center',
    },
    weatherText: {
        color: 'white',
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 8,
    },
    weatherIcon: {
        backgroundColor: 'rgba(255,255,255,0.2)',
        borderRadius: 16,
        padding: 12,
    },
    speedometerCard: {
        marginHorizontal: 20,
        marginBottom: 16,
    },
    speedometerContainer: {
        backgroundColor: 'white',
        borderRadius: 24,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.08,
        shadowRadius: 12,
        elevation: 4,
    },
    speedometerGradient: {
        borderRadius: 24,
        padding: 20,
    },
    speedometerHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    speedometerTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#111827',
    },
    speedometerSubtitle: {
        fontSize: 14,
        color: '#6b7280',
        marginTop: 2,
    },
    riskBadge: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 100,
        flexDirection: 'row',
        alignItems: 'center',
    },
    riskText: {
        fontWeight: 'bold',
        marginLeft: 6,
    },
    velocimetroWrapper: {
        alignItems: 'center',
        paddingVertical: 16,
    },
    statsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 24,
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: '#f3f4f6',
    },
    statItem: {
        alignItems: 'center',
        flex: 1,
    },
    statIcon: {
        width: 48,
        height: 48,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 8,
    },
    statLabel: {
        fontSize: 12,
        color: '#6b7280',
    },
    statValue: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#111827',
    },
    alertCard: {
        marginHorizontal: 20,
        marginBottom: 20,
    },
    alertGradient: {
        borderRadius: 24,
        padding: 20,
        shadowColor: '#2563eb',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 6,
    },
    alertRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    alertIcon: {
        backgroundColor: 'rgba(255,255,255,0.2)',
        borderRadius: 16,
        padding: 12,
        marginRight: 16,
    },
    alertContent: {
        flex: 1,
    },
    alertTitle: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 18,
        marginBottom: 4,
    },
    alertDescription: {
        color: 'rgba(255,255,255,0.9)',
        fontSize: 14,
    },
    alertBadgeContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 12,
    },
    alertBadge: {
        backgroundColor: 'rgba(255,255,255,0.3)',
        borderRadius: 100,
        paddingHorizontal: 12,
        paddingVertical: 6,
    },
    alertBadgeText: {
        color: 'white',
        fontSize: 12,
        fontWeight: '600',
    },
    mapCard: {
        marginHorizontal: 20,
        marginBottom: 24,
    },
    mapContainer: {
        backgroundColor: 'white',
        borderRadius: 24,
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 16,
        elevation: 8,
    },
    mapGradient: {
        padding: 16,
    },
    mapHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    mapTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#111827',
    },
    mapSubtitle: {
        fontSize: 12,
        color: '#6b7280',
        marginTop: 2,
    },
    refreshButton: {
        backgroundColor: '#f3f4f6',
        padding: 10,
        borderRadius: 12,
    },
    mapWrapper: {
        height: 288,
        width: '100%',
        borderRadius: 16,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#e5e7eb',
    },
    map: {
        flex: 1,
    },
    markerContainer: {
        alignItems: 'center',
    },
    marker: {
        width: 48,
        height: 48,
        borderRadius: 24,
        borderWidth: 3,
        borderColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
        elevation: 8,
    },
    markerText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 12,
    },
    markerLabel: {
        marginTop: 4,
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 20,
        overflow: 'hidden',
    },
    markerLabelText: {
        fontSize: 12,
        fontWeight: '500',
        color: '#1f2937',
    },
    selectedFarmCard: {
        marginTop: 16,
        padding: 16,
        backgroundColor: '#f9fafb',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#e5e7eb',
    },
    selectedFarmHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    selectedFarmInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    selectedFarmDot: {
        width: 12,
        height: 12,
        borderRadius: 6,
        marginRight: 12,
    },
    selectedFarmName: {
        fontWeight: 'bold',
        color: '#111827',
        fontSize: 16,
    },
    selectedFarmUpdate: {
        fontSize: 12,
        color: '#6b7280',
        marginTop: 2,
    },
    closeButton: {
        backgroundColor: 'white',
        padding: 6,
        borderRadius: 100,
    },
    selectedFarmStats: {
        flexDirection: 'row',
        marginTop: 16,
    },
    selectedFarmStat: {
        flex: 1,
    },
    statValueLarge: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#111827',
    },
    riskRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    riskValue: {
        fontSize: 18,
        fontWeight: 'bold',
        marginRight: 8,
    },
    riskBadgeSmall: {
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 100,
    },
    riskTextSmall: {
        fontSize: 10,
        fontWeight: '600',
    },
    importButton: {
        marginTop: 16,
        backgroundColor: '#059669',
        padding: 12,
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#059669',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 4,
    },
    importButtonText: {
        color: 'white',
        fontSize: 14,
        fontWeight: '600',
        marginLeft: 8,
    },
    legendContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginTop: 16,
        paddingTop: 8,
    },
    legendItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginRight: 12,
        marginBottom: 4,
    },
    legendDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
        marginRight: 6,
    },
    legendText: {
        fontSize: 12,
        color: '#4b5563',
    },
    footer: {
        alignItems: 'center',
        paddingBottom: 32,
        paddingTop: 8,
    },
    footerText: {
        fontSize: 12,
        color: '#9ca3af',
    },
});
